[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
eframe = "0.29.0"
egui = "0.29.0"
image = "0.25.2"
open = "5.3.0"
regex = "1.10.6"
serde = { version = "1.0.210", features = ["serde_derive"] }

